name: Publish CSS Shortcuts
on:
  workflow_dispatch:
  push:
    tags:
      - "@gcds-core/css-shortcuts*"
permissions:
  id-token: write
  contents: read

env:
  PACKAGE_NAME: '@gcds-core/css-shortcuts'

jobs:
  publish-css-shortcuts:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - run: npm run compile

      - name: Extract package version
        id: pkg
        run: echo "version=$(cat package.json | jq -r .version)" >> "$GITHUB_OUTPUT"

      - name: Publish @gcds-core/css-shortcuts to npm
        run: npm publish --ignore-scripts
        id: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Report deployment to Sentinel
        if: always()
        uses: cds-snc/sentinel-forward-data-action@main
        with:
          input_data: >-
             {"product":"design-system","sha":"${{ github.sha }}","version":"${{ steps.pkg.outputs.version }}","repository":"${{ github.repository }}","environment":"production","status":"${{ job.status }}"}
          log_type: CDS_Product_Deployment_Data
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Slack notify on failure
        if: failure()
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Publish @gcds-core/css-shortcuts failed: <https://github.com/cds-snc/gcds-css-shortcuts/actions/workflows/publish.yml|Publish CSS Shortcuts>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_OPS }}
